### ISSUE TITLE
Unable to build from examples shipped

### ISSUE THREAD

**Issue by mmussett** [project-flogo/stream#7]
**Current behavior (how does the issue manifest):**
Running flogo-cli to build example fails with error

**Expected behavior:**
Build should generate app
**Minimal steps to reproduce the problem (not required if feature enhancement):**

$ flogo create -f agg-flogo.json
Creating initial project structure, this might take a few seconds ...
$ cd stream
$ flogo prepare
$ flogo build
# stream/vendor/github.com/project-flogo/stream/pipeline
vendor/github.com/project-flogo/stream/pipeline/instance.go:21:13: undefined: channels.Channel
FATAL: command "build" failed: exit status 2

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
Performed update from GitHub today (26-Sep) of flogo-cli, flogo-contrib, and flogs-lib

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by mellistibco** [comment]
Hi @mmussett can you try creating the app with flogo-lib & flogo-contrib master?

```bash
flogo create -flv github.com/TIBCOSoftware/flogo-contrib/activity/log@master,github.com/TIBCOSoftware/flogo-lib/app/resource@master AppName
```

Also, you may need to manually install the activities that are being used by your pipeline using the `flogo install` cmd.

**Comment by mellistibco** [comment]
The CLI doesn't use the content of your local GOPATH (deps are pulled into a local src/vendor dir), it will pull in the latest based on the specified constraints. If you execute `flogo create` without any args, it will pull pull the latest tagged version from flogo-lib, flogo-contrib, etc. The -flv will add a constraint to go dep to ensure that the master branch is pulled.

**Comment by mellistibco** [comment]
@mmussett were you able to build the sample?
